### ISSUE TITLE
Pipelinewise documentation link broken

### ISSUE THREAD

**Issue by benwhite-birdiecare** [jmriego/pipelinewise-target-bigquery#1]
Hi there

The link to the pipelinewise documentation in the readme.md doc appears to be broken: https://transferwise.github.io/pipelinewise/connectors/targets/bigquery.html

Appreciate that it's early days for this target so maybe it's a placeholder? :-) 

Regards
Ben

**Comment by jmriego** [comment]
Hi,

yes, that's exactly it. I'm not part of TransferWise but they are checking this target and will hopefully upload it. That link is just a placeholder as you noticed :)

**Comment by benwhite-birdiecare** [comment]
Yeap that make sense :-). Thanks for your efforts here - I'm super interested in trying Pipelinewise with BQ!
