### ISSUE TITLE
Exception is thrown for non-fitting double precision values

### ISSUE THREAD

**Issue by asmisha** [jmriego/pipelinewise-target-bigquery#130]
File "/project/.meltano/loaders/target-bigquery/venv/lib/python3.9/site-packages/target_bigquery/db_sync.py", line 360, in records_to_avro 
result[name] = MAX_NUM if n > MAX_NUM else -MAX_NUM if n < -MAX_NUM else n.quantize(ALLOWED_DECIMALS)
decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]

Exception is thrown for non-fitting double precision values (for example 5.1e+19). 
Version 1.4.0

**Comment by jmriego** [comment]
hi @asmisha !
do you mind sending the lines that the tap give you when getting this error?
I have created an example with this number and it's working for me. I'm sure I'm not understanding the issue
```
{"type": "RECORD", "stream": "tap_mysql_test-test_table_bad_decimals", "record": {"C_pk": 6, "decimalColumn": 51000000000000000000}, "version": 1, "time_extracted": "2019-01-31T15:51:50.215998Z"}
```

**Comment by asmisha** [comment]
@jmriego I'm afraid I don't know how to do that;) To get this value i just wrapped line 360 with try-catch and logged the value of n.

I believe that it might not be the accurate representation of the number.

**Comment by jmriego** [comment]
probably the easiest way I can think of is to edit that same `db_sync.py` file and add after line 336 something like `print(record)`.
That would print every single record as it is received before they are processed. You could then check what's the last record that was printed before the error message appeared. Haven't tested that though!

Are you using PipelineWise, Meltano or just this target directly?

**Comment by asmisha** [comment]
The record is dict here and the value is printed the same as 5.1e+19.

I'm using 
    - name: target-bigquery
      variant: transferwise
      pip_url: pipelinewise-target-bigquery

**Comment by jmriego** [comment]
Oh of course, I didn't think if that. At least try to figure out what the line looks like. Then add a `print(line)` after the `for line in lines` in the `__init__.py` and search for which line is that

**Comment by asmisha** [comment]
```                            
try:
  result[name] = MAX_NUM if n > MAX_NUM else -MAX_NUM if n < -MAX_NUM else n.quantize(ALLOWED_DECIMALS)
except Exception as e: 
  logger.info("DEBUG value %s %s", name, n)
  raise e
 ```
DEBUG value total_supply 51000000000000000000

`LOGGER.info("debug line %s", line)`
{"type": "RECORD", "stream": "raw_data-coingecko_market_realtime", "record": {"total_supply": 5.1e+19}, "version": 1659258677787, "time_extracted": "2022-07-31T09:11:17.787912Z"}

**Comment by jmriego** [comment]
thanks for sending that!
In my opinion, this is an error on the tap. The total supply should send the value in integer format instead of scientific. I don't think that's something that is supported by the Singer standard.

Which tap is this? Can you open an issue with them? That last line you sent should tell them all they need. If you send me the link I can have a look at the discussion

**Comment by asmisha** [comment]
It's tap-postgres. This is a floating point field. It can contain double precision as well as integers. The problem is though that I can't make it numeric (https://github.com/transferwise/pipelinewise-target-postgres/issues/91)

In the end it works this way:
1. My custom tap fetches data from API and sends it to `target-postgres`. The field is "number" in the schema.
2. `target-postgres` can't make it numeric, it makes it double precision.
3. Then i use `tap-postgres` to extract these values and send it to `target-bigquery`
4. `target-bigquery` fails on double precision values that can't be quantized.

**Comment by jmriego** [comment]
maybe the easiest way would be then to use your tap to send data also to `target-bigquery`.
I don't think targets should accept numbers in scientific format. There's a big loss of accuracy there.

I can add an option that makes nulls all fields that this target cannot read, but that's probably the maximum that should be accepted.

Also, what I was saying is open an issue in `tap-postgres`. I'd expect no target can currently read the format that tap is extracting your number

**Comment by asmisha** [comment]
I don't think it's correct to set null to double precision values in scientific notation. 
I also don't think it's correct for the library to fail on some numeric values.
And I also don't see how changing the type can help. The Decimal is correctly created on the side of this target (`n = Decimal(flatten[name])`) and then it fails to send it to the BQ - that's the problem, not the data format.

However I agree that storing large values as double precision is not correct as well and is a subject for another issue (which I've already opened it). At this point i'm just wondering what's the correct way to send large values to BQ using this target.

**Comment by jmriego** [comment]
just to be clear, I'm not saying anything about changing data types, I just mean that instead of `"total_supply": 5.1e+19`, the `tap-postgres` should return `"total_supply": 51000000000000000000`

I'm currently loading big numbers from other taps and formats with no issues into BigQuery using this target. It's even part of the unit tests. Maybe there's a case I'm not accounting for, so if you can send me an example tap with correct data that this target is not able to load, I'm happy to have a look at it
