### ISSUE TITLE
Support Python 3.11

### ISSUE THREAD

**Issue by edgarrmondragon** [jmriego/pipelinewise-target-bigquery#157]
This seems to require bumping `fastavro` to `>=1.7.0`

EDIT: Blocked by https://github.com/transferwise/pipelinewise-singer-python dependency on `orjson==3.6.1`

**Comment by jmriego** [comment]
thanks for raising this. Yes, as soon as that's unblocked I'll get an alert and merge this. At the moment it would be too much work for me to replace the dependencies with [pipelinewise-singer-python](https://github.com/transferwise/pipelinewise-singer-python) for now but let's see how it progresses

**Comment by jmriego** [comment]
closing this as there seems to be nothing happening on that library, but feel free to reopen if that changes
