### ISSUE TITLE
Documentation mis-states name of batch size var

### ISSUE THREAD

**Issue by socketbox** [jmriego/pipelinewise-target-bigquery#21]
The code in `target_bigquery/__init__.py` checks for a variable named `batch_size_rows` and not `batch_size` as stated in the README file.

There are checks for configuration keys that are not mentioned in the documentation:

-`primary_key_required`
-`flush_all_streams`
-`parallelism`
-`max_parallelism`

**Comment by jmriego** [comment]
thanks @socketbox !
sorry, I just saw this issue. I have just added myself to watch all activity in this repo.
Thanks for the report. Those can come directly from https://github.com/transferwise/pipelinewise-target-snowflake

I'll review that they and possible some others are updated in the README and send the MR

**Comment by jmriego** [comment]
just sent that MR. Let me know if you find any issues!

**Comment by socketbox** [comment]
Sorry for the belated response. Thank you very much for doing this.
