### ISSUE TITLE
Existing schema not found, tries to recreate

### ISSUE THREAD

**Issue by AlexStansfield** [jmriego/pipelinewise-target-bigquery#5]
Unsure if this is a bug in the target or in Big Query itself.

We found that the query on this line:
https://github.com/transferwise/pipelinewise-target-bigquery/blob/f3bc0d69dcdff945fcaf52e3335df46f4b1e231c/target_bigquery/db_sync.py#L602

Doesn't return all the schemas, we had to prepend `INFORMATION_SCHEMA` with a region to find the schema we expected. This was working fine before and suddenly stopped working. We're not sure if this is expected behaviour of Big Query or not. 

Perhaps there is a safer api call that can be made to check if the schema exists?

**Comment by jmriego** [comment]
sorry @AlexStansfield! I didn't see this before.
I can do some testing during the weekend, but if you want to give it a go, this is another way of running this part of the code where it checks if the dataset exists and then creates it if needed:
```
        for schema in set([schema_name, temp_schema]):
            datasets = client.list_datasets()
            dataset_ids = [d.dataset_id.lower() for d in datasets]
            
            if schema.lower() not in dataset_ids:
                LOGGER.info("Schema '{}' does not exist. Creating...".format(schema))
                dataset = client.create_dataset(schema, exists_ok=True)
```

I haven't included any code about the table_columns_cache but this should help testing

**Comment by jmriego** [comment]
Hi @AlexStansfield ,
Can you give me more info about the error? When you are talking about region, do you mean a different project?
BigQuery would return the list of schemas in the default project https://cloud.google.com/bigquery/docs/information-schema-datasets

I'm guessing you have a service account that has one billing project but a different default project? Anything you think might be relevant let me know and I'll send the pull request. This should be a very easy change to make

**Comment by Tolsto** [comment]
Running into the same issue. Existing datasets are in the EU region but the information_schema query goes against US and will then also try to create the dataset in the US. This BigQuery loader lets you specify a location: https://github.com/adswerve/target-bigquery
Maybe that would also be an option here.

**Comment by jmriego** [comment]
I have added a location configuration that you can add on a project level in this branch: https://github.com/jmriego/pipelinewise-target-bigquery/tree/location

Can you test that and let me know if it fixes it for you?

**Comment by Tolsto** [comment]
Yes, works for me. Thank you.

**Comment by jmriego** [comment]
I have added that fix to the pull request #12 so after we merge this I'll ask TransferWise to close this issue

**Comment by AlexStansfield** [comment]
@jmriego I'm not sure if this is the same issue.

I'm trying to use the latest version of pipelinewise to put data in a new dataset in a asia-southeast1.

I have the location set to `asia-southeast1`. On initial run the data is all copied to a new dataset in bigquery as hoped, but then fails saying `Cannot sync table structure in BigQuery schema`.
 
Looking back in the logs it seems that it's trying to find the schema and failing even though it's there. So it tries to create it and gets an error.

Looking at the data set I see the it's in the US region. It seems like it's creating the data in `US` on initial sync and then trying to find the schema in the `asia-southeast1` later. If i remove the location option then everything works fine, but of course the data is in the US, not where we want it to be.

**Comment by AlexStansfield** [comment]
I think it might be the fastsync that's the issue. Looks like the fastsync is creating the data in US then the singer sync is failing to find the datasets in the `asia-southeast1` region.

**Comment by AlexStansfield** [comment]
I think I found the issue. I created an issue in the pipelinewise repo - https://github.com/transferwise/pipelinewise/issues/739

**Comment by judahrand** [comment]
I was also having this issue but have found that #68 fixed it for me.

**Comment by jmriego** [comment]
Now that #68 is merged, does that fix the issue for you @AlexStansfield ?
