### ISSUE TITLE
Append-only option for inserts

### ISSUE THREAD

**Issue by AlexStansfield** [jmriego/pipelinewise-target-bigquery#6]
The original singer.io target for big query only inserted updated rows. Using the _sdc_ metadata columns you could always query for the most recent version of a row.

The reason behind this being that Big Query charges a lot more for updates than inserts.

Is there any chance this sync method could be supported with a config option?

**Comment by AlexStansfield** [comment]
We looked at the code and saw it only does the update if a primary key is set for the table it's syncing. If we didn't set a primary key in the tap config it seems it would do this append-only method. Just wondering if that would have any other side effect.

**Comment by AlexStansfield** [comment]
Just realise we don't actually configure primary keys, I guess the tap is figuring it out itself.

**Comment by jmriego** [comment]
Hi @AlexStansfield ,
I copied the way this works from the Snowflake target if I'm remembering right. When this target receives data with a primary key (the primary key columns is read from the source by the taps, not by the target) it will do a merge of the rows.

@koszti would it be OK to add to this target a `ignore_primary_key` config variable? If set to `True` it would do only inserts. Do you have some other naming convention or preference about it?

**Comment by VinceLegendre** [comment]
+1 on this issue :)

**Comment by jmriego** [comment]
just added this in the new release! closing now
