### ISSUE TITLE
Schema with arrray of objects

### ISSUE THREAD

**Issue by vitoravancini** [jmriego/pipelinewise-target-bigquery#8]
Hello, I've been trying to use your target and I've reached a point where I couldn't make it work without changing a little code

It seems that schemas with arrays of objects do not work well, the temp is created correctly but the merge query fails.

I was able to make it work, if this is really an issue and not something that I misunderstood, I'd be happy to open a PR.

Thank you!

**Comment by jmriego** [comment]
hi @vitoravancini 
it seems like one of the recent commits in PipelineWise finally allowed me to finish all tests successfully so I'm going to try to merge what we have been using at my company for a while. All fixes including this should be in the last pull request: #12 

I know this is an old issue so sorry about that. I can talk to TransferWise about making me a main contributor in this repo so I get better alerts

**Comment by vitoravancini** [comment]
Nice @jmriego! I'll keep an eye out for when it gets merged

thanks!

**Comment by jmriego** [comment]
hi @vitoravancini ! now that I'm maintaining this repo I'm trying to figure out the issues that people are still having and do some cleaning up. Is this solved for you?
